version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: PHPREDIS-DOCKER-APP
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.9-alpine
    container_name: PHP-DOCKER-NGINX-V2
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
    links:
      - php:php
  php:
    build: ./
    restart: always
    expose:
      - "9000"
    links:
      - redis
    volumes:
      - /www/web:/usr/share/nginx/html
  redis:
    image: redis:latest
    container_name: REDIS-DOCKER-V1
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data
    command: redis-server --appendonly yes
